# Generated by Django 4.2 on 2025-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user_images/default_avatar.png', upload_to='user_images'),
        ),
    ]
