# Generated by Django 4.2 on 2025-07-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql = "INSERT INTO task_category (name, color, is_custom) VALUES ('Программирование', 'rgba(0, 0, 255, 0.8)', false);",
            reverse_sql= "DELETE FROM task_category WHERE name='Программирование';"
        )
    ]
